# act -j build -W ./.github/workflows/build-multiarch.yml --secret-file  .dockerhub.secrets
name: 'Build multiarch [BYTE]'

on:
  workflow_dispatch:
  # repository_dispatch:
    # types: [kimai_release]

jobs:
  build:
    strategy:
      matrix:
        type: [dev,prod]
        server: [fpm]
    env: 
      DOCKERHUB_REGISTRY: byteschneiderei/tobybatch-kimai2-docker
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install buildx
        uses: docker/setup-buildx-action@v2

      - name: Install lastversion
        run: sudo apt-get update -y; sudo apt-get install --no-install-recommends -y python3 python3-pip; pip install lastversion

      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: get lastest 1.x version
        id: remote_version
        run: echo "::set-output name=version::$(lastversion https://github.com/kevinpapst/kimai2 --only '~^1\.')"

      - name: build ${{ matrix.server }} ${{ matrix.type }}
        run: echo ${{ env.DOCKERHUB_REGISTRY }}:${{ matrix.type }}-${{ matrix.server }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            KIMAI=${{steps.remote_version.outputs.version}}
            TIMEZONE=Europe/London
            BASE=${{ matrix.server }}
          target: ${{ matrix.type }}
          platforms: linux/arm64,linux/amd64,linux/arm/v8,linux/arm/v7 #,linux/arm/v6
          tags: |
            ${{ env.DOCKERHUB_REGISTRY }}:${{ matrix.server }}-${{ matrix.type }}
            ${{ env.DOCKERHUB_REGISTRY }}:${{ matrix.server }}-${{steps.remote_version.outputs.version}}-${{ matrix.type }}
          push: true

  tag:
    runs-on: ubuntu-latest
    env: 
      DOCKERHUB_REGISTRY: byteschneiderei/tobybatch-kimai2-docker
    steps:

      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Pull images
        run: |
          docker pull ${{ env.DOCKERHUB_REGISTRY }}:fpm
          docker pull ${{ env.DOCKERHUB_REGISTRY }}:fpm-dev

      - name: Tag fpm
        run: |
          docker tag ${{ env.DOCKERHUB_REGISTRY }}:fpm ${{ env.DOCKERHUB_REGISTRY }}:fpm-prod
          docker push ${{ env.DOCKERHUB_REGISTRY }}:fpm

      - name: Tag fpm latest
        run: |
          docker tag ${{ env.DOCKERHUB_REGISTRY }}:fpm ${{ env.DOCKERHUB_REGISTRY }}:fpm-latest
          docker push ${{ env.DOCKERHUB_REGISTRY }}:fpm-latest

      - name: Tag latest
        run: |
          docker tag ${{ env.DOCKERHUB_REGISTRY }}:fpm ${{ env.DOCKERHUB_REGISTRY }}2:latest
          docker push ${{ env.DOCKERHUB_REGISTRY }}:latest

      - name: Tag prod
        run: |
          docker tag ${{ env.DOCKERHUB_REGISTRY }}:fpm ${{ env.DOCKERHUB_REGISTRY }}:prod
          docker push ${{ env.DOCKERHUB_REGISTRY }}:prod
